# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
OPENAI_API_KEY2 = "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"
OPENAI_API_KEY3 = "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"
OPENAI_API_KEY4 = "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"
OPENAI_API_KEY5 = "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"
OPENAI_API_KEY6 = "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"
OPENAI_API_KEY7 = "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"
OPENAI_API_KEY8 = "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"
OPENAI_API_KEY9 = "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"

